// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: agency.sql

package db

import (
	"context"
)

const getAgencyById = `-- name: GetAgencyById :one
SELECT id, name, url, timezone, phone, lang FROM agency
WHERE id = $1
`

func (q *Queries) GetAgencyById(ctx context.Context, id int32) (Agency, error) {
	row := q.db.QueryRowContext(ctx, getAgencyById, id)
	var i Agency
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Timezone,
		&i.Phone,
		&i.Lang,
	)
	return i, err
}
