// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"database/sql"
)

type Place struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Route struct {
	RouteID        string         `json:"route_id"`
	AgencyID       sql.NullInt32  `json:"agency_id"`
	RouteShortName sql.NullString `json:"route_short_name"`
	RouteLongName  sql.NullString `json:"route_long_name"`
	RouteType      sql.NullString `json:"route_type"`
	RouteColor     sql.NullString `json:"route_color"`
}

type Stop struct {
	StopID    int32          `json:"stop_id"`
	Code      sql.NullString `json:"code"`
	Name      string         `json:"name"`
	Lat       float64        `json:"lat"`
	Lon       float64        `json:"lon"`
	ZoneID    int32          `json:"zone_id"`
	Alias     sql.NullString `json:"alias"`
	Area      string         `json:"area"`
	Desc      sql.NullString `json:"desc"`
	LestX     float64        `json:"lest_x"`
	LestY     float64        `json:"lest_y"`
	ZoneName  sql.NullString `json:"zone_name"`
	Authority sql.NullString `json:"authority"`
}

type StopTime struct {
	TripID        int32         `json:"trip_id"`
	ArrivalTime   string        `json:"arrival_time"`
	DepartureTime string        `json:"departure_time"`
	StopID        int32         `json:"stop_id"`
	StopSequence  sql.NullInt32 `json:"stop_sequence"`
	PickupType    sql.NullInt32 `json:"pickup_type"`
	DropOffType   sql.NullInt32 `json:"drop_off_type"`
}

type Trip struct {
	RouteID              string         `json:"route_id"`
	ServiceID            int32          `json:"service_id"`
	TripID               int32          `json:"trip_id"`
	TripHeadsign         sql.NullString `json:"trip_headsign"`
	TripLongName         sql.NullString `json:"trip_long_name"`
	DirectionCode        sql.NullString `json:"direction_code"`
	WheelchairAccessible sql.NullInt32  `json:"wheelchair_accessible"`
}
