// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: route.sql

package db

import (
	"context"
)

const getRouteById = `-- name: GetRouteById :one
SELECT route_id, agency_id, route_short_name, route_long_name, route_type, route_color FROM route
WHERE route_id = $1
`

func (q *Queries) GetRouteById(ctx context.Context, routeID string) (Route, error) {
	row := q.db.QueryRowContext(ctx, getRouteById, routeID)
	var i Route
	err := row.Scan(
		&i.RouteID,
		&i.AgencyID,
		&i.RouteShortName,
		&i.RouteLongName,
		&i.RouteType,
		&i.RouteColor,
	)
	return i, err
}
