// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: route.sql

package db

import (
	"context"
)

const getRouteById = `-- name: GetRouteById :one
SELECT id, agency_id, short_name, long_name, color, competent_authority, "desc" FROM route
WHERE id = $1
`

func (q *Queries) GetRouteById(ctx context.Context, id int32) (Route, error) {
	row := q.db.QueryRowContext(ctx, getRouteById, id)
	var i Route
	err := row.Scan(
		&i.ID,
		&i.AgencyID,
		&i.ShortName,
		&i.LongName,
		&i.Color,
		&i.CompetentAuthority,
		&i.Desc,
	)
	return i, err
}
