// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: stop_time.sql

package db

import (
	"context"
	"database/sql"
)

const listTimesByStop = `-- name: ListTimesByStop :many
SELECT id, trip_id, arrival_time, departure_time, stop_id, stop_sequence FROM stop_time
WHERE stop_id = $1
`

func (q *Queries) ListTimesByStop(ctx context.Context, stopID sql.NullInt32) ([]StopTime, error) {
	rows, err := q.db.QueryContext(ctx, listTimesByStop, stopID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StopTime
	for rows.Next() {
		var i StopTime
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.ArrivalTime,
			&i.DepartureTime,
			&i.StopID,
			&i.StopSequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
