// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: trip.sql

package db

import (
	"context"
)

const listTripsById = `-- name: ListTripsById :many
SELECT route_id, service_id, trip_id, trip_headsign, trip_long_name, direction_code, wheelchair_accessible FROM trip
WHERE trip_id = $1
`

func (q *Queries) ListTripsById(ctx context.Context, tripID int32) ([]Trip, error) {
	rows, err := q.db.QueryContext(ctx, listTripsById, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trip{}
	for rows.Next() {
		var i Trip
		if err := rows.Scan(
			&i.RouteID,
			&i.ServiceID,
			&i.TripID,
			&i.TripHeadsign,
			&i.TripLongName,
			&i.DirectionCode,
			&i.WheelchairAccessible,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
